# Generated by Django 4.2 on 2023-04-20 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('puesto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Archivo_Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomrbe_real', models.CharField(max_length=255)),
                ('ruta', models.CharField(max_length=255)),
                ('archivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleado.archivo')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleado.empleado')),
            ],
        ),
    ]
